// packages/react/src/viewer.tsx
import * as bytemd from '@flicmd/bytemd'
import React, { useMemo, useEffect, useRef, FC } from 'react'

export interface ViewerProps extends bytemd.ViewerProps {}

export const Viewer: FC<ViewerProps> = ({
  value,
  sanitize,
  plugins,
  remarkRehype,
}) => {
  const elRef = useRef<HTMLDivElement>(null)
  const file = useMemo(() => {
    try {
      return bytemd
        .getProcessor({ sanitize, plugins, remarkRehype })
        .processSync(value)
    } catch (err) {
      console.error(err)
    }
  }, [value, sanitize, plugins, remarkRehype])

  useEffect(() => {
    const markdownBody = elRef.current
    if (!markdownBody || !file) return

    const cbs = plugins?.map(({ viewerEffect }) =>
      viewerEffect?.({ markdownBody, file })
    )
    return () => {
      cbs?.forEach((cb) => cb && cb())
    }
  }, [file, plugins])

  return (
    <div
      onClick={(e) => {
        const $ = e.target as HTMLElement
        if ($.tagName !== 'A') return

        const href = $.getAttribute('href')
        if (!href?.startsWith('#')) return

        elRef.current
          ?.querySelector('#user-content-' + href.slice(1))
          ?.scrollIntoView()
      }}
      ref={elRef}
      className="markdown-body"
      dangerouslySetInnerHTML={{ __html: file?.toString() ?? '' }}
    ></div>
  )
}

// packages/vue-next/src/viewer.vue
<template>
  <div
    v-html="file.toString()"
    className="markdown-body"
    @click="handleClick"
    ref="markdownBody"
  ></div>
</template>

<script lang="ts">
import {
  defineComponent,
  computed,
  watch,
  onMounted,
  onUnmounted,
  ref,
  Ref,
  nextTick,
} from 'vue'
import { getProcessor } from '@flicmd/bytemd'

export default defineComponent({
  props: ['value', 'plugins', 'sanitize', 'remarkRehype'],
  setup(props, ctx) {
    const markdownBody: Ref<HTMLElement | null> = ref(null)
    const cbs = ref([])
    const file = computed(() => {
      return getProcessor(props).processSync(props.value)
    })

    const needUpdate = computed(() => {
      return [file, props.plugins, props.sanitize, props.remarkRehype]
    })

    watch(
      needUpdate,
      () => {
        off()
        nextTick(() => {
          on()
        })
      },
      { deep: true }
    )

    onMounted(() => {
      on()
    })

    onUnmounted(() => {
      off()
    })

    const handleClick = (e: MouseEvent) => {
      const $ = e.target as HTMLElement
      if ($.tagName !== 'A') return

      const href = $.getAttribute('href')
      if (!href || !href.startsWith('#')) return

      const dest = (markdownBody.value as HTMLElement).querySelector(
        '#user-content-' + href.slice(1)
      )
      if (dest) dest.scrollIntoView()
    }

    const off = () => {
      if (cbs.value.length) {
        cbs.value.forEach((cb: any) => cb && cb())
      }
    }

    const on = () => {
      if (props.plugins && file) {
        cbs.value = props.plugins.map(
          ({ viewerEffect }: any) =>
            viewerEffect &&
            viewerEffect({ markdownBody: markdownBody.value, file })
        )
      }
    }

    return { markdownBody, file, handleClick }
  },
})
</script>
